version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.10
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - export LC_ALL="en_US.utf8"
      - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/g0z6e9p3/write-metrics

  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image for your-app...
      - docker build -t write-metrics:latest .
      - docker tag write-metrics:latest public.ecr.aws/g0z6e9p3/write-metrics:latest

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push public.ecr.aws/g0z6e9p3/write-metrics:latest
