version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/g0z6e9p3/write-metrics
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image for metrics_to_rds...
      - docker build -t public.ecr.aws/g0z6e9p3/write-metrics:latest -f Dockerfile.updaterds .
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push public.ecr.aws/g0z6e9p3/write-metrics:latest
